import type { Metadata } from "next"
import EcuadorServiceClient, { type EcuadorServiceItem } from "@/components/ecuador-service-client"

export const metadata: Metadata = {
  title: "Formulaciones Bacterianas y Bioinsumos en Ecuador | AS Labs",
  description: "Desarrollo, fermentación, estandarización, estabilidad, producción piloto y control de calidad para formulaciones bacterianas y bioinsumos agrícolas.",
  keywords: ["formulaciones bacterianas Ecuador", "bioinsumos Quito", "fermentación bacteriana Ecuador", "biofertilizantes Ecuador", "control calidad bacteriano Quito", "producción piloto bioinsumos", "estabilidad formulaciones microbianas"],
  alternates: { canonical: "https://aslaboratorios.com/ecuador/formulaciones-bacterianas", languages: { "es-EC": "https://aslaboratorios.com/ecuador/formulaciones-bacterianas" } },
  openGraph: { locale: "es_EC", url: "https://aslaboratorios.com/ecuador/formulaciones-bacterianas", title: "Formulaciones Bacterianas | AS Labs Ecuador", description: "Desarrollo microbiológico desde la cepa hasta la evaluación piloto.", images: ["/servicios/image.png"] },
}

const formulationServices: EcuadorServiceItem[] = [
  { title: "Diseño de formulaciones bacterianas", category: "Desarrollo", summary: "Construcción de una formulación según microorganismo, cultivo, aplicación y condiciones de uso.", scope: ["Definición de concentración objetivo", "Selección preliminar de vehículo", "Criterios técnicos de conservación"] },
  { title: "Fermentación líquida", category: "Fermentación", summary: "Evaluación y ajuste de condiciones para producir biomasa o metabolitos en sistemas líquidos.", scope: ["Selección de medio de cultivo", "Seguimiento de crecimiento", "Recuperación o acondicionamiento de biomasa"] },
  { title: "Fermentación sólida", category: "Fermentación", summary: "Desarrollo de procesos sobre sustratos sólidos compatibles con el microorganismo y objetivo productivo.", scope: ["Selección de sustrato", "Control de humedad e incubación", "Evaluación de rendimiento y viabilidad"] },
  { title: "Optimización de medios de cultivo", category: "Optimización", summary: "Comparación de fuentes nutricionales y condiciones para mejorar crecimiento, concentración o productividad.", scope: ["Diseño comparativo de medios", "Curvas de crecimiento", "Selección de condición recomendada"] },
  { title: "Estandarización de concentración microbiana", category: "Control", summary: "Definición de un procedimiento reproducible para ajustar la concentración de la preparación.", scope: ["Método de recuento", "Rango de aceptación", "Registro por lote o ensayo"] },
  { title: "Recuento, pureza y viabilidad", category: "Control", summary: "Evaluación microbiológica del producto o cultivo para conocer concentración, pureza y células viables.", scope: ["Recuento microbiológico", "Control de contaminación", "Resultado de viabilidad según método"] },
  { title: "Producción piloto de bioinsumos", category: "Escalamiento", summary: "Lotes piloto para evaluar repetibilidad y parámetros críticos antes de una escala mayor.", scope: ["Plan de lote piloto", "Monitoreo de variables críticas", "Informe de resultados y observaciones"] },
  { title: "Desarrollo de biofertilizantes", category: "Aplicación", summary: "Evaluación de microorganismos y formulaciones orientadas a nutrición, rizósfera y promoción vegetal.", scope: ["Definición de objetivo agronómico", "Selección de microorganismo o consorcio", "Prototipo sujeto a validación"] },
  { title: "Desarrollo de bioestimulantes microbianos", category: "Aplicación", summary: "Diseño experimental de productos microbianos orientados a vigor, establecimiento o respuesta al estrés.", scope: ["Definición de atributo esperado", "Preparación de prototipos", "Plan de evaluación biológica"] },
  { title: "Formulación de consorcios microbianos", category: "Desarrollo", summary: "Evaluación de compatibilidad para combinar cepas con funciones complementarias en una preparación.", scope: ["Compatibilidad entre microorganismos", "Proporciones iniciales", "Seguimiento de estabilidad del consorcio"] },
  { title: "Selección de portadores y adyuvantes", category: "Formulación", summary: "Comparación de materiales de soporte, protectores o coadyuvantes compatibles con la cepa.", scope: ["Evaluación de compatibilidad", "Impacto sobre viabilidad", "Selección de alternativa técnica"] },
  { title: "Estabilidad y vida útil preliminar", category: "Formulación", summary: "Seguimiento programado para observar cambios de concentración, pureza y desempeño durante almacenamiento.", scope: ["Condiciones y tiempos acordados", "Puntos de control", "Tendencia y criterio preliminar"] },
  { title: "Control microbiológico de lotes", category: "Control", summary: "Verificación de parámetros microbiológicos definidos para lotes experimentales o productivos.", scope: ["Plan de muestreo", "Recuento y pureza", "Reporte comparativo con criterios"] },
  { title: "Documentación para transferencia y escalamiento", category: "Escalamiento", summary: "Organización de parámetros, controles y registros técnicos generados durante el desarrollo.", scope: ["Resumen del proceso evaluado", "Variables críticas identificadas", "Recomendaciones para siguiente escala"] },
]

export default function FormulacionesBacterianasEcuadorPage() {
  return <EcuadorServiceClient kind="formulations" eyebrow="Formulaciones bacterianas" title="Microorganismos convertidos en soluciones aplicables" description="Diseñamos y evaluamos formulaciones bacterianas a partir de una necesidad concreta: cultivo objetivo, forma de aplicación, concentración, viabilidad y condiciones de conservación." image="/servicios/image.png" services={formulationServices} methods={["Caracterización inicial del microorganismo", "Selección y optimización de condiciones de crecimiento", "Estandarización de biomasa y concentración", "Recuento, pureza y viabilidad microbiana", "Evaluación de portadores, adyuvantes y estabilidad", "Definición de condiciones de conservación y escalamiento"]} deliverables={["Informe técnico del lote o ensayo", "Parámetros de formulación evaluados", "Resultados de concentración, viabilidad y pureza", "Registro de controles aplicados", "Observaciones de estabilidad y compatibilidad", "Recomendaciones para conservación y siguiente escala"]} />
}
