// Datos de Cepas ATCC desde catálogo - Solo BSL-1
export const cepasATCC = [
  {
    id: "atcc-1",
    nombre: "Bacillus licheniformis",
    codigo: "ATCC 14580",
    cientifico: "Bacillus licheniformis (Weigmann) Chester",
    bsl: "BSL-1",
    categoria: "Bacilos & Esporulados",
    productFormat: "Freeze-dried",
    strainDesignation: "[46, NCIB 9375, NCTC 10341, NRS 1264]",
    depositedAs: "Bacillus licheniformis",
    typeStrain: "Sí",
    cantidad: "1 unidad",
    referencia: "ATCC-14580",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Bacillus%20licheniformis%20ATCC%2014580",
    disponibilidad: true,
  },
  {
    id: "atcc-2",
    nombre: "Bacillus subtilis",
    codigo: "ATCC 6051",
    cientifico: "Bacillus subtilis (Ehrenberg) Cohn",
    bsl: "BSL-1",
    categoria: "Bacilos & Esporulados",
    productFormat: "Freeze-dried",
    strainDesignation: "Marburg strain [ATCC 6051-U, DSM 10, NCIB 3610, NCTC 3610]",
    depositedAs: "Bacillus subtilis",
    typeStrain: "Sí",
    cantidad: "1 unidad",
    referencia: "ATCC-6051",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Bacillus%20subtilis%20ATCC%206051",
    disponibilidad: true,
  },
  {
    id: "atcc-3",
    nombre: "Escherichia coli",
    codigo: "ATCC 25922-MINI-PACK",
    cientifico: "Escherichia coli",
    bsl: "BSL-1",
    categoria: "Control de Calidad & Esterilización",
    productFormat: "Frozen glycerol stock",
    strainDesignation: "FDA strain Seattle 1946",
    depositedAs: "Escherichia coli",
    typeStrain: "No",
    cantidad: "6 viales de 200 µL",
    referencia: "ATCC-25922",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Escherichia%20coli%20ATCC%2025922",
    disponibilidad: true,
  },
  {
    id: "atcc-4",
    nombre: "Geobacillus stearothermophilus",
    codigo: "ATCC 7953",
    cientifico: "Geobacillus stearothermophilus",
    bsl: "BSL-1",
    categoria: "Control de Calidad & Esterilización",
    productFormat: "Freeze-dried",
    strainDesignation: "",
    depositedAs: "Geobacillus stearothermophilus",
    typeStrain: "No",
    cantidad: "1 unidad",
    referencia: "ATCC-7953",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Geobacillus%20stearothermophilus%20ATCC%207953",
    disponibilidad: true,
  },
  {
    id: "atcc-5",
    nombre: "Geobacillus stearothermophilus",
    codigo: "ATCC 12980",
    cientifico: "Geobacillus stearothermophilus",
    bsl: "BSL-1",
    categoria: "Control de Calidad & Esterilización",
    productFormat: "Freeze-dried",
    strainDesignation: "NCA 26",
    depositedAs: "Geobacillus stearothermophilus",
    typeStrain: "Sí",
    cantidad: "1 unidad",
    referencia: "ATCC-12980",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Geobacillus%20stearothermophilus%20ATCC%2012980",
    disponibilidad: true,
  },
  {
    id: "atcc-6",
    nombre: "Geobacillus stearothermophilus",
    codigo: "ATCC 10149",
    cientifico: "Geobacillus stearothermophilus",
    bsl: "BSL-1",
    categoria: "Alimentos & Fermentación",
    productFormat: "Freeze-dried",
    strainDesignation: "NRS T15 [JCM 11297]",
    depositedAs: "Geobacillus stearothermophilus",
    typeStrain: "No",
    cantidad: "1 unidad",
    referencia: "ATCC-10149",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Geobacillus%20stearothermophilus%20ATCC%2010149",
    disponibilidad: true,
  },
  {
    id: "atcc-7",
    nombre: "Heyndrickxia coagulans",
    codigo: "ATCC 7050",
    cientifico: "Heyndrickxia coagulans (Hammer) Narsing Rao et al.",
    bsl: "BSL-1",
    categoria: "Alimentos & Fermentación",
    productFormat: "Freeze-dried",
    strainDesignation: "NRS 609 [NCIB 9365, NCTC 10334]",
    depositedAs: "Antes: Weizmannia coagulans / Bacillus coagulans",
    typeStrain: "Sí",
    cantidad: "1 unidad",
    referencia: "ATCC-7050",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Bacillus%20coagulans%20ATCC%207050",
    disponibilidad: true,
  },
  {
    id: "atcc-8",
    nombre: "Lacticaseibacillus casei",
    codigo: "ATCC 393",
    cientifico: "Lacticaseibacillus casei (Orla-Jensen) Zheng et al.",
    bsl: "BSL-1",
    categoria: "Alimentos & Fermentación",
    productFormat: "Freeze-dried",
    strainDesignation: "03 [7, IAM 12473, Orland L-323, R.P. Tittsler 303]",
    depositedAs: "Antes: Lactobacillus casei",
    typeStrain: "Sí",
    cantidad: "1 unidad",
    referencia: "ATCC-393",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Lacticaseibacillus%20casei%20ATCC%20393",
    disponibilidad: true,
  },
  {
    id: "atcc-9",
    nombre: "Lactobacillus acidophilus",
    codigo: "ATCC 4356",
    cientifico: "Lactobacillus acidophilus (Moro) Hansen and Mocquot",
    bsl: "BSL-1",
    categoria: "Alimentos & Fermentación",
    productFormat: "Freeze-dried",
    strainDesignation: "Scav [IFO 13951, M. Rogosa 210X, NCIB 8690, P.A. Hansen L 917]",
    depositedAs: "Lactobacillus acidophilus",
    typeStrain: "Sí",
    cantidad: "1 unidad",
    referencia: "ATCC-4356",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Lactobacillus%20acidophilus%20ATCC%204356",
    disponibilidad: true,
  },
  {
    id: "atcc-10",
    nombre: "Paenibacillus polymyxa",
    codigo: "ATCC 842",
    cientifico: "Paenibacillus polymyxa",
    bsl: "BSL-1",
    categoria: "Biotecnología & Agricultura",
    productFormat: "Freeze-dried",
    strainDesignation: "BUCSAV 162 / CCM 1459 / NCIB 8158 / NCTC 10343",
    depositedAs: "Paenibacillus polymyxa",
    typeStrain: "Sí",
    cantidad: "1 unidad",
    referencia: "ATCC-842",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Paenibacillus%20polymyxa%20ATCC%20842",
    disponibilidad: true,
  },
  {
    id: "atcc-11",
    nombre: "Pseudomonas putida",
    codigo: "ATCC 12633",
    cientifico: "Pseudomonas putida",
    bsl: "BSL-1",
    categoria: "Biotecnología & Agricultura",
    productFormat: "",
    strainDesignation: "ATCC 12633 / IFO 14164",
    depositedAs: "Pseudomonas putida",
    typeStrain: "Sí",
    cantidad: "1 unidad",
    referencia: "ATCC-12633",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Pseudomonas%20putida%20ATCC%2012633",
    disponibilidad: true,
  },
  {
    id: "atcc-12",
    nombre: "Serratia marcescens subsp. marcescens",
    codigo: "ATCC 13880",
    cientifico: "Serratia marcescens subsp. marcescens",
    bsl: "BSL-1",
    categoria: "Bacilos & Esporulados",
    productFormat: "Freeze-dried",
    strainDesignation: "BS 303 [CDC 813-60, NCIB 9155, NCTC 10211]",
    depositedAs: "Serratia marcescens subsp. marcescens",
    typeStrain: "Sí",
    cantidad: "1 unidad",
    referencia: "ATCC-13880",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Serratia%20marcescens%20ATCC%2013880",
    disponibilidad: true,
  },
  {
    id: "atcc-13",
    nombre: "Priestia megaterium",
    codigo: "ATCC 14581-MINI-PACK",
    cientifico: "Priestia megaterium",
    bsl: "BSL-1",
    categoria: "Bacilos & Esporulados",
    productFormat: "Frozen glycerol stock",
    strainDesignation: "BCRC 10608 / DSM 32 / NCTC 10342",
    depositedAs: "Antes: Bacillus megaterium",
    typeStrain: "Sí",
    cantidad: "6 viales",
    referencia: "ATCC-14581",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Priestia%20megaterium%20ATCC%2014581",
    disponibilidad: true,
  },
  {
    id: "atcc-14",
    nombre: "Bacillus spizizenii",
    codigo: "ATCC 6633-MINI-PACK",
    cientifico: "Bacillus spizizenii (Nakamura et al.) Dunlap et al.",
    bsl: "BSL-1",
    categoria: "Control de Calidad & Esterilización",
    productFormat: "Frozen",
    strainDesignation: "NRS 231",
    depositedAs: "Antes: Bacillus subtilis subsp. spizizenii",
    typeStrain: "No",
    cantidad: "6 viales listos para usar; 200 µL en stock de glicerol",
    referencia: "ATCC-6633",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Bacillus%20spizizenii%20ATCC%206633",
    disponibilidad: true,
  },
  {
    id: "atcc-15",
    nombre: "Bacillus atrophaeus",
    codigo: "ATCC 9372",
    cientifico: "Bacillus atrophaeus Nakamura",
    bsl: "BSL-1",
    categoria: "Control de Calidad & Esterilización",
    productFormat: "Freeze-dried",
    strainDesignation: "NRS 1221A",
    depositedAs: "Bacillus atrophaeus",
    typeStrain: "No",
    cantidad: "1 unidad",
    referencia: "ATCC-9372",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Bacillus%20atrophaeus%20ATCC%209372",
    disponibilidad: true,
  },
  {
    id: "atcc-16",
    nombre: "Micrococcus luteus",
    codigo: "ATCC 4698",
    cientifico: "Micrococcus luteus",
    bsl: "BSL-1",
    categoria: "Control de Calidad & Esterilización",
    productFormat: "Freeze-dried",
    strainDesignation: "",
    depositedAs: "Micrococcus luteus",
    typeStrain: "",
    cantidad: "1 unidad",
    referencia: "ATCC-4698",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Micrococcus%20luteus%20ATCC%204698",
    disponibilidad: true,
  },
  {
    id: "atcc-17",
    nombre: "Bacillus amyloliquefaciens",
    codigo: "ATCC 23350",
    cientifico: "Bacillus amyloliquefaciens (Fukumoto) Priest et al.",
    bsl: "BSL-1",
    categoria: "Biotecnología & Agricultura",
    productFormat: "Freeze-dried",
    strainDesignation: "F [IFO 15535]",
    depositedAs: "Bacillus amyloliquefaciens",
    typeStrain: "Sí",
    cantidad: "1 unidad",
    referencia: "ATCC-23350",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Bacillus%20amyloliquefaciens%20ATCC%2023350",
    disponibilidad: true,
  },
  {
    id: "atcc-18",
    nombre: "Bacillus sp.",
    codigo: "ATCC 14884",
    cientifico: "Bacillus sp.",
    bsl: "BSL-1",
    categoria: "Bacilos & Esporulados",
    productFormat: "Freeze-dried",
    strainDesignation: "NCTC 8241 [CCM 2218, DSM 361, NCIB 8982]",
    depositedAs: "Bacillus sp.",
    typeStrain: "No",
    cantidad: "1 unidad",
    referencia: "ATCC-14884",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Bacillus%20pumilus%20ATCC%2014884",
    disponibilidad: true,
  },
  {
    id: "atcc-19",
    nombre: "Bacillus thuringiensis",
    codigo: "ATCC 10792",
    cientifico: "Bacillus thuringiensis Berliner",
    bsl: "BSL-1",
    categoria: "Biotecnología & Agricultura",
    productFormat: "Freeze-dried",
    strainDesignation: "CCUG 7429 / CIP 53.137 / DSM 2046 / HAMBI 478 / LMG 7138 / NRRL HD-735",
    depositedAs: "Bacillus thuringiensis",
    typeStrain: "Sí",
    cantidad: "1 unidad",
    referencia: "ATCC-10792",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Bacillus%20thuringiensis%20ATCC%2010792",
    disponibilidad: true,
  },
  {
    id: "atcc-20",
    nombre: "Lactiplantibacillus plantarum",
    codigo: "ATCC 14917",
    cientifico: "Lactiplantibacillus plantarum",
    bsl: "BSL-1",
    categoria: "Alimentos & Fermentación",
    productFormat: "Freeze-dried",
    strainDesignation: "Lp 39 [IAM 12477]",
    depositedAs: "Antes: Lactobacillus plantarum subsp. plantarum",
    typeStrain: "Sí",
    cantidad: "1 unidad",
    referencia: "ATCC-14917",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Lactiplantibacillus%20plantarum%20ATCC%2014917",
    disponibilidad: true,
  },
  {
    id: "atcc-21",
    nombre: "Lactococcus lactis subsp. lactis",
    codigo: "ATCC 19435",
    cientifico: "Lactococcus lactis subsp. lactis",
    bsl: "BSL-1",
    categoria: "Alimentos & Fermentación",
    productFormat: "Freeze-dried",
    strainDesignation: "NCTC 6681 [DSM 20481, NCDO 604, NCIB 6681, OJ]",
    depositedAs: "Lactococcus lactis subsp. lactis",
    typeStrain: "Sí",
    cantidad: "1 unidad",
    referencia: "ATCC-19435",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Lactococcus%20lactis%20ATCC%2019435",
    disponibilidad: true,
  },
  {
    id: "atcc-22",
    nombre: "Streptococcus thermophilus",
    codigo: "ATCC 19258",
    cientifico: "Streptococcus thermophilus Orla-Jensen",
    bsl: "BSL-1",
    categoria: "Alimentos & Fermentación",
    productFormat: "Freeze-dried",
    strainDesignation: "NCDO 573 [NCIMB 8510, CNCTC 28/89, DSM 20617, CCUG 21957, CIP 102303, LMG 6896]",
    depositedAs: "Streptococcus thermophilus",
    typeStrain: "Sí",
    cantidad: "1 unidad",
    referencia: "ATCC-19258",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Streptococcus%20thermophilus%20ATCC%2019258",
    disponibilidad: true,
  },
  {
    id: "atcc-23",
    nombre: "Azotobacter vinelandii",
    codigo: "ATCC 12837",
    cientifico: "Azotobacter vinelandii Lipman",
    bsl: "BSL-1",
    categoria: "Biotecnología & Agricultura",
    productFormat: "Freeze-dried",
    strainDesignation: "3a",
    depositedAs: "Azotobacter vinelandii",
    typeStrain: "No",
    cantidad: "1 unidad",
    referencia: "ATCC-12837",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Azotobacter%20vinelandii%20ATCC%2012837",
    disponibilidad: true,
  },
  {
    id: "atcc-24",
    nombre: "Bacillus subtilis",
    codigo: "ATCC 49822",
    cientifico: "Bacillus subtilis",
    bsl: "BSL-1",
    categoria: "Control de Calidad & Esterilización",
    productFormat: "Freeze-dried",
    strainDesignation: "",
    depositedAs: "Bacillus subtilis subsp. subtilis",
    typeStrain: "No",
    cantidad: "1 unidad",
    referencia: "ATCC-49822",
    link: "https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=Bacillus%20subtilis%20ATCC%2049822",
    disponibilidad: true,
  },
]
