import {
  Leaf,
  FlaskConical,
  TreePine,
  Apple,
  Cherry,
  Sprout,
} from "lucide-react"
import { Plantin } from "./types"

export const plantines: Plantin[] = [
  // Bananos - Todos a S/. 4.50
  {
    id: "banano-cavendish",
    name: "Banano Cavendish Valery",
    category: "Bananos",
    description: "Variedad comercial de alta productividad y excelente calidad de fruto para exportación.",
    features: ["Alta productividad", "Resistente a vientos", "Fruto de calidad comercial", "Ideal para exportación"],
    available: true,
    icon: Leaf,
    image: "/plantines/pagina18.webp",
    price: "S/. 4.50",
    yield: "40-50 ton/ha",
    harvestTime: "12-14 meses",
    profitability: "Alta",
    resistance: ["Vientos fuertes", "Sequías moderadas"],
    technicalData: {
      climate: "Tropical húmedo, temperatura 26-30°C",
      soil: "Franco-arcilloso, pH 6.0-7.5, bien drenado",
      irrigation: "1,200-1,500 mm anuales, riego por goteo recomendado",
      fertilization: "NPK 15-15-15, aplicación cada 3 meses",
      spacing: "2.5m x 2.5m (1,600 plantas/ha)",
      maintenance: "Deshoje mensual, control de malezas, tutorado",
      harvest: "Racimos de 18-22 kg, corte cuando dedos están llenos",
      storage: "Temperatura 13-15°C, humedad 85-90%",
      diseases: ["Sigatoka negra", "Mal de Panamá", "Nematodos"],
      benefits: ["Alto contenido de potasio", "Rica en vitaminas B6 y C", "Fibra dietética"],
    },
  },
  {
    id: "banano-williams",
    name: "Banano Williams",
    category: "Bananos",
    description: "Variedad tradicional con excelente sabor y gran adaptabilidad a diferentes climas.",
    features: ["Sabor excepcional", "Buena adaptabilidad", "Ciclo productivo estable", "Mercado establecido"],
    available: true,
    icon: Leaf,
    image: "/plantines/pagina19.webp",
    price: "S/. 4.50",
    yield: "35-45 ton/ha",
    harvestTime: "11-13 meses",
    profitability: "Media-Alta",
    resistance: ["Cambios climáticos", "Suelos diversos"],
    technicalData: {
      climate: "Tropical y subtropical, temperatura 24-28°C",
      soil: "Franco-limoso, pH 5.5-7.0, drenaje moderado",
      irrigation: "1,000-1,300 mm anuales, tolerante a sequía",
      fertilization: "NPK 12-12-17, aplicación bimensual",
      spacing: "2.0m x 2.0m (2,500 plantas/ha)",
      maintenance: "Poda de hijuelos, fertilización regular",
      harvest: "Racimos de 15-20 kg, maduración uniforme",
      storage: "Temperatura 12-14°C, ventilación adecuada",
      diseases: ["Antracnosis", "Pudrición de corona"],
      benefits: ["Sabor dulce intenso", "Textura cremosa", "Larga vida útil"],
    },
  },
  {
    id: "baby-banano",
    name: "Baby Banano",
    category: "Bananos",
    description: "Banano de tamaño pequeño con alto valor comercial y demanda creciente en mercados premium.",
    features: ["Tamaño compacto", "Dulzor concentrado", "Alto valor comercial", "Demanda premium"],
    available: true,
    icon: Leaf,
    image: "/plantines/pagina20.webp",
    price: "S/. 4.50",
    yield: "25-35 ton/ha",
    harvestTime: "10-12 meses",
    profitability: "Muy Alta",
    resistance: ["Plagas comunes", "Enfermedades foliares"],
    technicalData: {
      climate: "Tropical cálido, temperatura 27-32°C",
      soil: "Franco-arenoso, pH 6.0-7.0, excelente drenaje",
      irrigation: "800-1,200 mm anuales, riego controlado",
      fertilization: "NPK 10-10-10 + micronutrientes",
      spacing: "1.5m x 1.5m (4,400 plantas/ha)",
      maintenance: "Control de densidad, poda selectiva",
      harvest: "Racimos de 8-12 kg, dedos de 8-10 cm",
      storage: "Temperatura 14-16°C, empaque especializado",
      diseases: ["Trips", "Cochinilla"],
      benefits: ["Alto contenido de azúcar", "Ideal para niños", "Snack saludable"],
    },
  },
  {
    id: "banano-tailandes",
    name: "Banano Tailandés",
    category: "Bananos",
    description: "Variedad exótica con características únicas, perfecta para mercados especializados.",
    features: ["Sabor único", "Textura especial", "Variedad exótica", "Nicho de mercado"],
    available: true,
    icon: Leaf,
    image: "/plantines/pagina21.webp",
    price: "S/. 4.50",
    yield: "30-40 ton/ha",
    harvestTime: "12-15 meses",
    profitability: "Muy Alta",
    resistance: ["Hongos", "Bacterias"],
    technicalData: {
      climate: "Tropical húmedo, temperatura 25-29°C",
      soil: "Rico en materia orgánica, pH 6.5-7.5",
      irrigation: "1,400-1,800 mm anuales, humedad constante",
      fertilization: "Fertilización orgánica + NPK 14-14-14",
      spacing: "2.0m x 2.5m (2,000 plantas/ha)",
      maintenance: "Manejo orgánico, control biológico",
      harvest: "Racimos de 12-18 kg, sabor aromático",
      storage: "Temperatura 13-15°C, maduración controlada",
      diseases: ["Resistente a Sigatoka", "Tolerante a virus"],
      benefits: ["Propiedades antioxidantes", "Sabor exótico", "Textura única"],
    },
  },
  {
    id: "banano-fusarium",
    name: "Banano Fusarium Resistente",
    category: "Bananos",
    description: "Revolución genética: banano completamente resistente a Fusarium R4T, el futuro de la bananicultura.",
    features: ["100% Resistente a Fusarium", "Tecnología de vanguardia", "Proyecto revolucionario", "Futuro asegurado"],
    available: false,
    isResearch: true,
    icon: FlaskConical,
    image: "/plantines/pagina22.webp",
    price: "En desarrollo",
    yield: "50-60 ton/ha (proyectado)",
    harvestTime: "11-13 meses (proyectado)",
    profitability: "Revolucionaria",
    resistance: ["Fusarium R4T", "Múltiples patógenos"],
    technicalData: {
      climate: "Adaptable a múltiples climas tropicales",
      soil: "Tolerante a suelos infectados con Fusarium",
      irrigation: "Eficiente uso del agua, 1,000-1,400 mm",
      fertilization: "Optimizada para máxima resistencia",
      spacing: "2.5m x 2.5m (1,600 plantas/ha)",
      maintenance: "Mínimo uso de fungicidas",
      harvest: "Proyectado: racimos de 20-25 kg",
      storage: "Vida útil extendida",
      diseases: ["Inmune a Fusarium R4T", "Resistente a Sigatoka"],
      benefits: ["Sostenibilidad ambiental", "Seguridad alimentaria", "Innovación genética"],
    },
  },
  // Plátanos - A cotizar
  {
    id: "platano-rojo",
    name: "Plátano Rojo",
    category: "Plátanos",
    description: "Plátano de coloración rojiza con alto contenido nutricional y excelente precio de mercado.",
    features: ["Color distintivo", "Alto valor nutricional", "Resistente a plagas", "Precio premium"],
    available: true,
    icon: TreePine,
    image: "/plantines/pagina23.webp",
    price: "A cotizar",
    yield: "20-30 ton/ha",
    harvestTime: "14-16 meses",
    profitability: "Alta",
    resistance: ["Plagas foliares", "Nematodos"],
    technicalData: {
      climate: "Tropical cálido, temperatura 26-30°C",
      soil: "Franco-arcilloso, rico en hierro, pH 6.0-7.0",
      irrigation: "1,200-1,600 mm anuales, drenaje excelente",
      fertilization: "NPK 15-5-20 + hierro quelado",
      spacing: "3.0m x 3.0m (1,100 plantas/ha)",
      maintenance: "Control de hijuelos, fertilización rica en hierro",
      harvest: "Racimos de 15-25 kg, coloración rojiza intensa",
      storage: "Temperatura 12-14°C, evitar golpes",
      diseases: ["Antracnosis", "Pudrición bacteriana"],
      benefits: ["Alto contenido de antocianinas", "Propiedades antioxidantes", "Rico en hierro"],
    },
  },
  {
    id: "platano-malayo",
    name: "Plátano Malayo",
    category: "Plátanos",
    description: "Variedad de origen asiático con excelente adaptación y alta productividad comercial.",
    features: ["Origen asiático", "Adaptación tropical", "Productividad alta", "Resistencia natural"],
    available: true,
    icon: TreePine,
    image: "/plantines/pagina24.webp",
    price: "A cotizar",
    yield: "25-35 ton/ha",
    harvestTime: "13-15 meses",
    profitability: "Media-Alta",
    resistance: ["Clima tropical", "Humedad alta"],
    technicalData: {
      climate: "Tropical húmedo, temperatura 24-28°C",
      soil: "Franco-limoso, pH 5.5-6.5, bien drenado",
      irrigation: "1,300-1,700 mm anuales, tolerante a humedad",
      fertilization: "NPK 12-12-17 + materia orgánica",
      spacing: "2.5m x 3.0m (1,300 plantas/ha)",
      maintenance: "Poda regular, control de densidad",
      harvest: "Racimos de 18-28 kg, frutos grandes",
      storage: "Temperatura 13-15°C, ventilación natural",
      diseases: ["Sigatoka amarilla", "Virus del mosaico"],
      benefits: ["Textura firme", "Sabor suave", "Versatilidad culinaria"],
    },
  },
  {
    id: "platano-azul",
    name: "Plátano Azul",
    category: "Plátanos",
    description: "Variedad única con tonalidades azuladas, perfecta para mercados gourmet y restaurantes.",
    features: ["Coloración única", "Sabor distintivo", "Variedad rara", "Mercado gourmet"],
    available: true,
    icon: TreePine,
    image: "/plantines/pagina25.webp",
    price: "A cotizar",
    yield: "18-25 ton/ha",
    harvestTime: "15-17 meses",
    profitability: "Muy Alta",
    resistance: ["Enfermedades comunes", "Estrés hídrico"],
    technicalData: {
      climate: "Tropical moderado, temperatura 22-26°C",
      soil: "Rico en minerales, pH 6.0-7.0, drenaje perfecto",
      irrigation: "1,000-1,400 mm anuales, riego controlado",
      fertilization: "NPK 10-10-10 + micronutrientes especiales",
      spacing: "2.0m x 2.5m (2,000 plantas/ha)",
      maintenance: "Manejo especializado, control de calidad",
      harvest: "Racimos de 10-18 kg, coloración azul-violeta",
      storage: "Temperatura 14-16°C, empaque premium",
      diseases: ["Resistente a la mayoría de patógenos"],
      benefits: ["Antocianinas únicas", "Sabor exótico", "Alto valor gourmet"],
    },
  },
  // Otros cultivos - A cotizar
  {
    id: "pina-golden",
    name: "Piña Golden",
    category: "Otros Cultivos",
    description: "Piña de variedad dorada con dulzor excepcional, perfecta para exportación y jugos premium.",
    features: ["Dulzor excepcional", "Alta jugosidad", "Calidad premium", "Exportación"],
    available: true,
    icon: Apple,
    image: "/plantines/pagina19.webp",
    price: "A cotizar",
    yield: "60-80 ton/ha",
    harvestTime: "18-20 meses",
    profitability: "Alta",
    resistance: ["Pudrición del corazón", "Cochinilla"],
    technicalData: {
      climate: "Tropical seco, temperatura 24-30°C",
      soil: "Franco-arenoso, pH 4.5-6.5, drenaje excelente",
      irrigation: "800-1,200 mm anuales, riego por goteo",
      fertilization: "NPK 12-4-12 + boro y zinc",
      spacing: "1.2m x 0.3m (25,000 plantas/ha)",
      maintenance: "Control de malezas, aplicación de hormonas",
      harvest: "Frutos de 1.5-2.5 kg, color dorado intenso",
      storage: "Temperatura 7-13°C, humedad 85-90%",
      diseases: ["Pudrición negra", "Cochinilla harinosa"],
      benefits: ["Alto contenido de vitamina C", "Enzimas digestivas", "Bromelina natural"],
    },
  },
  {
    id: "pitahaya",
    name: "Pitahaya",
    category: "Otros Cultivos",
    description: "Fruta del dragón con demanda explosiva en mercados internacionales y precios excepcionales.",
    features: ["Alto valor comercial", "Propiedades nutricionales", "Demanda creciente", "Superfruit"],
    available: true,
    icon: Cherry,
    image: "/plantines/pagina20.webp",
    price: "A cotizar",
    yield: "15-25 ton/ha",
    harvestTime: "24-30 meses",
    profitability: "Excepcional",
    resistance: ["Sequías", "Temperaturas extremas"],
    technicalData: {
      climate: "Tropical seco, temperatura 18-26°C",
      soil: "Cactáceo, pH 6.0-7.5, drenaje perfecto",
      irrigation: "600-1,000 mm anuales, resistente a sequía",
      fertilization: "NPK 8-8-8 + calcio y magnesio",
      spacing: "3.0m x 3.0m (1,100 plantas/ha)",
      maintenance: "Poda de formación, tutorado en espaldera",
      harvest: "Frutos de 300-600g, pulpa blanca o roja",
      storage: "Temperatura 10-15°C, vida útil 2-3 semanas",
      diseases: ["Antracnosis", "Pudrición bacteriana"],
      benefits: ["Antioxidantes naturales", "Bajo en calorías", "Rico en vitamina C"],
    },
  },
  {
    id: "fresa",
    name: "Fresa",
    category: "Otros Cultivos",
    description: "Fresas de alta calidad con producción continua y resistencia superior a enfermedades.",
    features: ["Alta calidad", "Resistente a enfermedades", "Producción continua", "Ciclo corto"],
    available: true,
    icon: Sprout,
    image: "/plantines/pagina18.webp",
    price: "A cotizar",
    yield: "40-60 ton/ha",
    harvestTime: "4-6 meses",
    profitability: "Muy Alta",
    resistance: ["Botrytis", "Antracnosis", "Ácaros"],
    technicalData: {
      climate: "Templado frío, temperatura 15-25°C",
      soil: "Franco-arenoso, pH 5.5-6.5, rico en materia orgánica",
      irrigation: "400-600 mm anuales, riego por goteo",
      fertilization: "NPK 10-10-10 + calcio y boro",
      spacing: "0.3m x 0.3m (110,000 plantas/ha)",
      maintenance: "Deshoje, control de estolones, mulching",
      harvest: "Frutos de 15-25g, cosecha cada 2-3 días",
      storage: "Temperatura 0-2°C, humedad 90-95%",
      diseases: ["Botrytis cinerea", "Antracnosis", "Oidium"],
      benefits: ["Alto contenido de vitamina C", "Antioxidantes", "Ácido fólico"],
    },
  },
]

export const categories = ["Todos", "Bananos", "Plátanos", "Otros Cultivos"]
