import {
  Leaf,
  FlaskConical,
  TreePine,
  Apple,
  Cherry,
  Sprout,
} from "lucide-react"
import { Plantin } from "./types"

export const plantines: Plantin[] = [ 
  {
    id: "arandano-asar",
    name: "Arándano InVitro ASAR",
    category: "Frutales",
    description: "Plantas obtenidas por micropropagación in vitro, genéticamente uniformes y libres de patógenos.",
    features: ["Alta sanidad vegetal", "Uniformidad fenotípica", "Mejor establecimiento", "Mayor eficiencia productiva"],
    available: true,
    isProduction: true,
    icon: Cherry,
    image: "/plantines/arandano.jpeg",
    price: "A cotizar",
    yield: "12–20 ton/ha",
    harvestTime: "18–24 meses",
    profitability: "Alta",
    resistance: ["Botrytis cinerea", "Phytophthora spp.", "Colletotrichum spp."],
    technicalData: {
      climate: "Templado–frío, temperatura óptima 12–22 °C",
      soil: "Franco–arenoso a franco, pH ácido 4.5–5.5, alto contenido de materia orgánica, excelente drenaje",
      irrigation: "700–1,000 mm anuales, riego por goteo con manejo estricto de conductividad y pH",
      fertilization: "NPK balanceado bajo en nitratos, suplementado con calcio, magnesio, hierro y micronutrientes quelatados",
      spacing: "1.0–1.2 m entre plantas × 2.5–3.0 m entre hileras (2,800–4,000 plantas/ha)",
      maintenance: "Poda de formación y producción, control de malezas, mulching orgánico o plástico, monitoreo nutricional y fitosanitario",
      harvest: "Frutos de 1.5–3.0 g, recolección manual escalonada",
      storage: "Temperatura 0–1 °C, humedad relativa 90–95%, atmósfera controlada según destino comercial",
      diseases: ["Botrytis cinerea", "Phytophthora spp.", "Colletotrichum spp."],
      benefits: ["Alta sanidad vegetal", "Uniformidad fenotípica", "Mejor establecimiento y vigor inicial", "Mayor eficiencia productiva"],
    },
  },
  // Ornamentales - Amaryllis
  {
    id: "amaryllis-asam",
    name: "Amaryllis in vitro ASAM",
    category: "Ornamentales",
    description: "Plantas micropropagadas in vitro (Hippeastrum spp.), uniformes y con alta sanidad fitosanitaria.",
    features: ["Alta uniformidad varietal", "Reducción de patógenos", "Mejor establecimiento", "Escalabilidad para producción masiva"],
    available: true,
    isProduction: true,
    icon: Leaf,
    image: "/plantines/amarillys.jpeg",
    price: "A cotizar",
    yield: "-",
    harvestTime: "Planta con flores",
    profitability: "Alta",
    resistance: ["Fusarium oxysporum", "Botrytis cinerea", "Stagonospora curtisii"],
    technicalData: {
      climate: "Templado, temperatura óptima 18–26 °C (evitar <12 °C sostenido)",
      soil: "Franco–arenoso, pH 6.0–7.0, alta materia orgánica, drenaje elevado",
      irrigation: "Moderado, preferible por goteo; evitar encharcamiento y periodos prolongados de saturación",
      fertilization: "NPK balanceado con énfasis en potasio; suplementación con calcio, magnesio y micronutrientes (B, Zn, Fe)",
      spacing: "0.20–0.30 m entre plantas × 0.40–0.60 m entre hileras (dependiente del calibre objetivo del bulbo)",
      maintenance: "Control de malezas, deshoje sanitario, tutorado si se induce floración, manejo de bulbo (curado y selección por calibre)",
      harvest: "Se entrega planta desarrollada con flores o para transplante en campo",
      storage: "Curado y selección por calibre según destino comercial",
      diseases: ["Pudrición basal por Fusarium", "Botrytis cinerea", "Manchas foliares por Stagonospora"],
      benefits: ["Alta uniformidad varietal", "Reducción de carga inicial de patógenos", "Mejor establecimiento y crecimiento temprano", "Escalabilidad para producción masiva"],
    },
  }, 
  {
    id: "orquidea-aso1",
    name: "Orquídeas In Vitro ASO1",
    category: "Ornamentales",
    description: "Plantines in vitro en frasco, listos para aclimatación. Material clonal bajo condiciones controladas.",
    features: ["Alta uniformidad", "Producción clonal", "Calidad de planta", "Costos optimizados"],
    available: true,
    isProduction: true,
    icon: Leaf,
    image: "/plantines/orquideasASORQ.jpeg",
    price: "S/. 79.90 x Maceta",
    yield: "3 a 10 flores",
    harvestTime: "Frío/Calor",
    profitability: "3 a 10 flores",
    resistance: ["Hongos", "Bacterias", "Plagas comunes"],
    technicalData: {
      climate: "Invernadero o área protegida con buena ventilación y luz filtrada. Temperatura templado-cálida estable.",
      soil: "Alta aireación y drenaje (corteza, musgo, fibra de coco, carbón vegetal), libre de patógenos y sales.",
      irrigation: "Frecuente y moderado; permitir secado parcial del sustrato; agua de baja salinidad.",
      fertilization: "Soluciones balanceadas para ornamentales, en dosis bajas y fraccionadas.",
      spacing: "Separación suficiente para circulación de aire y control sanitario.",
      maintenance: "Eliminación de material senescente, desinfección de herramientas, monitoreo semanal.",
      harvest: "Floración dependiente de género y manejo; se optimiza con estabilidad ambiental.",
      storage: "Aclimatación: transición gradual desde in vitro con aumento progresivo de ventilación.",
      diseases: ["Manchas foliares", "Pudriciones blandas", "Trips", "Ácaros", "Cochinillas"],
      benefits: ["Alta uniformidad morfológica", "Desarrollo inicial controlado", "Producción escalable"],
    },
  }, 
  {
    id: "banano-cavendish",
    name: "Banano Invitro ASC5",
    category: "Bananos",
    description: "Banano Cavendish Valery",
    features: ["Alta productividad", "Resistente a vientos", "Fruto de calidad comercial", "Ideal para exportación"],
    available: true,
    icon: Leaf,
    image: "/plantines/pagina18.webp",
    price: "S/. 4.50",
    yield: "40-50 ton/ha",
    harvestTime: "12-14 meses",
    profitability: "Alta",
    resistance: ["Vientos fuertes", "Sequías moderadas"],
    technicalData: {
      climate: "Tropical húmedo, temperatura 26-30°C",
      soil: "Franco-arcilloso, pH 6.0-7.5, bien drenado",
      irrigation: "1,200-1,500 mm anuales, riego por goteo recomendado",
      fertilization: "NPK 15-15-15, aplicación cada 3 meses",
      spacing: "2.5m x 2.5m (1,600 plantas/ha)",
      maintenance: "Deshoje mensual, control de malezas, tutorado",
      harvest: "Racimos de 18-22 kg, corte cuando dedos están llenos",
      storage: "Temperatura 13-15°C, humedad 85-90%",
      diseases: ["Sigatoka negra", "Mal de Panamá", "Nematodos"],
      benefits: ["Alto contenido de potasio", "Rica en vitaminas B6 y C", "Fibra dietética"],
    },
  },
  {
    id: "banano-williams",
    name: "Banano Invitro ASWG",
    category: "Bananos",
    description: "Banano Cavendish Williams",
    features: ["Sabor excepcional", "Buena adaptabilidad", "Ciclo productivo estable", "Mercado establecido"],
    available: true,
    icon: Leaf,
    image: "/plantines/pagina19.webp",
    price: "S/. 4.50",
    yield: "35-45 ton/ha",
    harvestTime: "11-13 meses",
    profitability: "Media-Alta",
    resistance: ["Cambios climáticos", "Suelos diversos"],
    technicalData: {
      climate: "Tropical y subtropical, temperatura 24-28°C",
      soil: "Franco-limoso, pH 5.5-7.0, drenaje moderado",
      irrigation: "1,000-1,300 mm anuales, tolerante a sequía",
      fertilization: "NPK 12-12-17, aplicación bimensual",
      spacing: "2.0m x 2.0m (2,500 plantas/ha)",
      maintenance: "Poda de hijuelos, fertilización regular",
      harvest: "Racimos de 15-20 kg, maduración uniforme",
      storage: "Temperatura 12-14°C, ventilación adecuada",
      diseases: ["Antracnosis", "Pudrición de corona"],
      benefits: ["Sabor dulce intenso", "Textura cremosa", "Larga vida útil"],
    },
  },
  {
    id: "baby-banano",
    name: "Banano Invitro ASBBG",
    category: "Bananos",
    description: "Banano Baby",
    features: ["Tamaño compacto", "Dulzor concentrado", "Alto valor comercial", "Demanda premium"],
    available: true,
    icon: Leaf,
    image: "/plantines/bananoBabyBBG.jpeg",
    price: "S/. 4.50",
    yield: "25-35 ton/ha",
    harvestTime: "10-12 meses",
    profitability: "Muy Alta",
    resistance: ["Plagas comunes", "Enfermedades foliares"],
    technicalData: {
      climate: "Tropical cálido, temperatura 27-32°C",
      soil: "Franco-arenoso, pH 6.0-7.0, excelente drenaje",
      irrigation: "800-1,200 mm anuales, riego controlado",
      fertilization: "NPK 10-10-10 + micronutrientes",
      spacing: "1.5m x 1.5m (4,400 plantas/ha)",
      maintenance: "Control de densidad, poda selectiva",
      harvest: "Racimos de 8-12 kg, dedos de 8-10 cm",
      storage: "Temperatura 14-16°C, empaque especializado",
      diseases: ["Trips", "Cochinilla"],
      benefits: ["Alto contenido de azúcar", "Ideal para niños", "Snack saludable"],
    },
  },
  {
    id: "banano-tailandes",
    name: "Platano Invitro ASTHAI",
    category: "Bananos",
    description: "Plátano Thai",
    features: ["Sabor único", "Textura especial", "Variedad exótica", "Nicho de mercado"],
    available: true,
    icon: Leaf,
    image: "/plantines/pagina21.webp",
    price: "S/. 4.50",
    yield: "30-40 ton/ha",
    harvestTime: "12-15 meses",
    profitability: "Muy Alta",
    resistance: ["Hongos", "Bacterias"],
    technicalData: {
      climate: "Tropical húmedo, temperatura 25-29°C",
      soil: "Rico en materia orgánica, pH 6.5-7.5",
      irrigation: "1,400-1,800 mm anuales, humedad constante",
      fertilization: "Fertilización orgánica + NPK 14-14-14",
      spacing: "2.0m x 2.5m (2,000 plantas/ha)",
      maintenance: "Manejo orgánico, control biológico",
      harvest: "Racimos de 12-18 kg, sabor aromático",
      storage: "Temperatura 13-15°C, maduración controlada",
      diseases: ["Resistente a Sigatoka", "Tolerante a virus"],
      benefits: ["Propiedades antioxidantes", "Sabor exótico", "Textura única"],
    },
  },
  {
    id: "banano-fusarium",
    name: "Banano Fusarium Resistente",
    category: "Bananos",
    description: "Revolución genética: banano completamente resistente a Fusarium R4T, el futuro de la bananicultura.",
    features: ["100% Resistente a Fusarium", "Tecnología de vanguardia", "Proyecto revolucionario", "Futuro asegurado"],
    available: false,
    isResearch: true,
    icon: FlaskConical,
    image: "/plantines/investigacion.jpeg",
    price: "En desarrollo",
    yield: "50-60 ton/ha (proyectado)",
    harvestTime: "11-13 meses (proyectado)",
    profitability: "Revolucionaria",
    resistance: ["Fusarium R4T", "Múltiples patógenos"],
    technicalData: {
      climate: "Adaptable a múltiples climas tropicales",
      soil: "Tolerante a suelos infectados con Fusarium",
      irrigation: "Eficiente uso del agua, 1,000-1,400 mm",
      fertilization: "Optimizada para máxima resistencia",
      spacing: "2.5m x 2.5m (1,600 plantas/ha)",
      maintenance: "Mínimo uso de fungicidas",
      harvest: "Proyectado: racimos de 20-25 kg",
      storage: "Vida útil extendida",
      diseases: ["Inmune a Fusarium R4T", "Resistente a Sigatoka"],
      benefits: ["Sostenibilidad ambiental", "Seguridad alimentaria", "Innovación genética"],
    },
  },
  // Plátanos - A cotizar
  {
    id: "platano-rojo",
    name: "Plátano invitro ASRG",
    category: "Plátanos",
    description: "Plátano Rojo o Malayo",
    features: ["Color distintivo", "Alto valor nutricional", "Resistente a plagas", "Precio premium"],
    available: true,
    icon: TreePine,
    image: "/plantines/pagina23.webp",
    price: "A cotizar",
    yield: "20-30 ton/ha",
    harvestTime: "14-16 meses",
    profitability: "Alta",
    resistance: ["Plagas foliares", "Nematodos"],
    technicalData: {
      climate: "Tropical cálido, temperatura 26-30°C",
      soil: "Franco-arcilloso, rico en hierro, pH 6.0-7.0",
      irrigation: "1,200-1,600 mm anuales, drenaje excelente",
      fertilization: "NPK 15-5-20 + hierro quelado",
      spacing: "3.0m x 3.0m (1,100 plantas/ha)",
      maintenance: "Control de hijuelos, fertilización rica en hierro",
      harvest: "Racimos de 15-25 kg, coloración rojiza intensa",
      storage: "Temperatura 12-14°C, evitar golpes",
      diseases: ["Antracnosis", "Pudrición bacteriana"],
      benefits: ["Alto contenido de antocianinas", "Propiedades antioxidantes", "Rico en hierro"],
    },
  },
  {
    id: "platano-azul",
    name: "Banano Invitro ASAZ",
    category: "Plátanos",
    description: "Banano Azul",
    features: ["Coloración única", "Sabor distintivo", "Variedad rara", "Mercado gourmet"],
    available: true,
    icon: TreePine,
    image: "/plantines/pagina20.webp",
    price: "A cotizar",
    yield: "18-25 ton/ha",
    harvestTime: "15-17 meses",
    profitability: "Muy Alta",
    resistance: ["Enfermedades comunes", "Estrés hídrico"],
    technicalData: {
      climate: "Tropical moderado, temperatura 22-26°C",
      soil: "Rico en minerales, pH 6.0-7.0, drenaje perfecto",
      irrigation: "1,000-1,400 mm anuales, riego controlado",
      fertilization: "NPK 10-10-10 + micronutrientes especiales",
      spacing: "2.0m x 2.5m (2,000 plantas/ha)",
      maintenance: "Manejo especializado, control de calidad",
      harvest: "Racimos de 10-18 kg, coloración azul-violeta",
      storage: "Temperatura 14-16°C, empaque premium",
      diseases: ["Resistente a la mayoría de patógenos"],
      benefits: ["Antocianinas únicas", "Sabor exótico", "Alto valor gourmet"],
    },
  },
  {
    id: "platano-manzano",
    name: "Platano invitro ASMZ",
    category: "Plátanos",
    description: "Plátano Manzano",
    features: ["Sabor dulce característico", "Textura firme", "Alta productividad", "Resistente a plagas"],
    available: true,
    icon: TreePine,
    image: "/plantines/pagina25.webp",
    price: "A cotizar",
    yield: "22-32 ton/ha",
    harvestTime: "14-16 meses",
    profitability: "Alta",
    resistance: ["Enfermedades foliares", "Estrés climático"],
    technicalData: {
      climate: "Tropical húmedo, temperatura 24-28°C",
      soil: "Franco-limoso, pH 6.0-7.0, bien drenado",
      irrigation: "1,200-1,500 mm anuales, riego uniforme",
      fertilization: "NPK 14-14-14 + micronutrientes",
      spacing: "2.5m x 2.5m (1,600 plantas/ha)",
      maintenance: "Poda regular, control de hijuelos",
      harvest: "Racimos de 16-24 kg, frutos medianos",
      storage: "Temperatura 12-15°C, ventilación adecuada",
      diseases: ["Sigatoka", "Antracnosis"],
      benefits: ["Rico en potasio", "Sabor característico", "Textura única"],
    },
  },
  {
    id: "platano-dominico",
    name: "Plátano invitro ASDG",
    category: "Plátanos",
    description: "Plátano Dominico Harton",
    features: ["Variedad tradicional", "Gran tamaño", "Excelente para cocción", "Alta demanda local"],
    available: true,
    icon: TreePine,
    image: "/plantines/pagina23.webp",
    price: "A cotizar",
    yield: "28-38 ton/ha",
    harvestTime: "13-15 meses",
    profitability: "Media-Alta",
    resistance: ["Vientos fuertes", "Sequías"],
    technicalData: {
      climate: "Tropical cálido, temperatura 25-30°C",
      soil: "Franco-arcilloso, pH 6.0-7.5, drenaje bueno",
      irrigation: "1,300-1,600 mm anuales, tolerante a sequía",
      fertilization: "NPK 15-5-20 + materia orgánica",
      spacing: "3.0m x 3.0m (1,100 plantas/ha)",
      maintenance: "Control de densidad, fertilización regular",
      harvest: "Racimos de 20-30 kg, frutos grandes",
      storage: "Temperatura 13-16°C, ambiente ventilado",
      diseases: ["Sigatoka amarilla", "Nematodos"],
      benefits: ["Alto contenido energético", "Versátil en cocina", "Rica en almidón"],
    },
  },
  // Otros cultivos - A cotizar
  {
    id: "pina-golden",
    name: "Piña Golden",
    category: "Otros Cultivos",
    description: "Piña de variedad dorada con dulzor excepcional, perfecta para exportación y jugos premium.",
    features: ["Dulzor excepcional", "Alta jugosidad", "Calidad premium", "Exportación"],
    available: true,
    icon: Apple,
    image: "/plantines/pinaGolden.jpeg",
    price: "A cotizar",
    yield: "60-80 ton/ha",
    harvestTime: "18-20 meses",
    profitability: "Alta",
    resistance: ["Pudrición del corazón", "Cochinilla"],
    technicalData: {
      climate: "Tropical seco, temperatura 24-30°C",
      soil: "Franco-arenoso, pH 4.5-6.5, drenaje excelente",
      irrigation: "800-1,200 mm anuales, riego por goteo",
      fertilization: "NPK 12-4-12 + boro y zinc",
      spacing: "1.2m x 0.3m (25,000 plantas/ha)",
      maintenance: "Control de malezas, aplicación de hormonas",
      harvest: "Frutos de 1.5-2.5 kg, color dorado intenso",
      storage: "Temperatura 7-13°C, humedad 85-90%",
      diseases: ["Pudrición negra", "Cochinilla harinosa"],
      benefits: ["Alto contenido de vitamina C", "Enzimas digestivas", "Bromelina natural"],
    },
  },
  {
    id: "pitahaya",
    name: "Pitahaya",
    category: "Otros Cultivos",
    description: "Fruta del dragón con demanda explosiva en mercados internacionales y precios excepcionales.",
    features: ["Alto valor comercial", "Propiedades nutricionales", "Demanda creciente", "Superfruit"],
    available: true,
    icon: Cherry,
    image: "/plantines/pitahaya.jpeg  ",
    price: "A cotizar",
    yield: "15-25 ton/ha",
    harvestTime: "24-30 meses",
    profitability: "Excepcional",
    resistance: ["Sequías", "Temperaturas extremas"],
    technicalData: {
      climate: "Tropical seco, temperatura 18-26°C",
      soil: "Cactáceo, pH 6.0-7.5, drenaje perfecto",
      irrigation: "600-1,000 mm anuales, resistente a sequía",
      fertilization: "NPK 8-8-8 + calcio y magnesio",
      spacing: "3.0m x 3.0m (1,100 plantas/ha)",
      maintenance: "Poda de formación, tutorado en espaldera",
      harvest: "Frutos de 300-600g, pulpa blanca o roja",
      storage: "Temperatura 10-15°C, vida útil 2-3 semanas",
      diseases: ["Antracnosis", "Pudrición bacteriana"],
      benefits: ["Antioxidantes naturales", "Bajo en calorías", "Rico en vitamina C"],
    },
  },
  {
    id: "fresa",
    name: "Fresa",
    category: "Otros Cultivos",
    description: "Fresas de alta calidad con producción continua y resistencia superior a enfermedades.",
    features: ["Alta calidad", "Resistente a enfermedades", "Producción continua", "Ciclo corto"],
    available: true,
    icon: Sprout,
    image: "/plantines/fresa.jpeg",
    price: "A cotizar",
    yield: "40-60 ton/ha",
    harvestTime: "4-6 meses",
    profitability: "Muy Alta",
    resistance: ["Botrytis", "Antracnosis", "Ácaros"],
    technicalData: {
      climate: "Templado frío, temperatura 15-25°C",
      soil: "Franco-arenoso, pH 5.5-6.5, rico en materia orgánica",
      irrigation: "400-600 mm anuales, riego por goteo",
      fertilization: "NPK 10-10-10 + calcio y boro",
      spacing: "0.3m x 0.3m (110,000 plantas/ha)",
      maintenance: "Deshoje, control de estolones, mulching",
      harvest: "Frutos de 15-25g, cosecha cada 2-3 días",
      storage: "Temperatura 0-2°C, humedad 90-95%",
      diseases: ["Botrytis cinerea", "Antracnosis", "Oidium"],
      benefits: ["Alto contenido de vitamina C", "Antioxidantes", "Ácido fólico"],
    },
  },
]

export const categories = ["Todos", "Frutales", "Ornamentales", "Bananos", "Plátanos", "Otros Cultivos"]
