"use client"

import Image from "next/image"
import Link from "next/link"
import { motion } from "framer-motion"
import { ArrowRight, Atom, BadgeCheck, Building2, Dna, FlaskConical, MapPin, Microscope, Sparkles } from "lucide-react"
import { Navbar } from "@/components/navbar"
import EcuadorFooter from "@/components/ecuador-footer"
import { WhatsAppContact } from "@/components/whatsapp-contact"

const solutions = [
  { href: "/ecuador/biologia-molecular", icon: Dna, eyebrow: "Diagnóstico e identificación", title: "Biología molecular", description: "PCR, qPCR, RT-PCR, identificación por secuenciación, genética vegetal y soporte molecular para investigación.", image: "/research/research-lab.png", tags: ["PCR y qPCR", "16S e ITS", "Secuenciación", "ADN y ARN"] },
  { href: "/ecuador/formulaciones-bacterianas", icon: FlaskConical, eyebrow: "Biotecnología microbiana", title: "Formulaciones bacterianas", description: "Desarrollo, estandarización y control de formulaciones bacterianas para aplicaciones productivas y proyectos especiales.", image: "/servicios/image.png", tags: ["Fermentación", "Bioinsumos", "Viabilidad", "Control de calidad"] },
]

export default function EcuadorClient() {
  return (
    <div className="min-h-screen overflow-hidden bg-[#f5f7f4] font-[var(--font-poppins)] text-[#143229]">
      <Navbar overlay />
      <main>
        <section data-navbar-theme="dark" className="relative overflow-hidden bg-[#071d18] px-5 pb-20 pt-28 text-white sm:px-8 sm:pb-24 sm:pt-32">
          <div className="absolute inset-0 opacity-35 [background-image:linear-gradient(rgba(114,215,181,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(114,215,181,.08)_1px,transparent_1px)] [background-size:58px_58px]" />
          <div className="absolute -left-40 top-16 h-96 w-96 rounded-full bg-[#1e8f72]/20 blur-[120px]" /><div className="absolute -right-40 -top-24 h-[520px] w-[520px] rounded-full bg-[#e5bd45]/10 blur-[130px]" />
          <div className="relative mx-auto grid max-w-7xl items-center gap-10 lg:min-h-[530px] lg:grid-cols-[1fr_.94fr]">
            <motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.7,ease:[.16,1,.3,1]}}>
              <div className="inline-flex items-center gap-2 rounded-full border border-[#e5bd45]/30 bg-[#e5bd45]/10 px-4 py-2 text-[10px] font-bold uppercase tracking-[.2em] text-[#f2d77e]"><span>🇪🇨</span>Nueva sede · Quito</div>
              <p className="mt-7 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-[#92e3c7]"><Sparkles className="h-4 w-4" />AS Labs Ecuador</p>
              <h1 className="mt-4 max-w-3xl text-balance text-4xl font-semibold leading-[1.02] tracking-[-.05em] sm:text-6xl">Ciencia especializada, ahora más cerca</h1>
              <p className="mt-5 max-w-xl text-sm leading-7 text-white/65 sm:text-base">Llegamos a Ecuador con un portafolio enfocado: biología molecular y formulaciones bacterianas para decisiones respaldadas por evidencia.</p>
              <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="#servicios-ecuador" className="group inline-flex min-h-14 items-center justify-center gap-3 rounded-full bg-[#8ce3c6] px-7 text-sm font-bold text-[#09261f] transition hover:-translate-y-1 hover:bg-[#a9efd8]">Conocer servicios<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link><WhatsAppContact mode="modal" message="Hola, quisiera información sobre AS Labs Ecuador." className="inline-flex min-h-14 items-center justify-center rounded-full border border-white/20 bg-white/[.07] px-7 text-sm font-bold text-white backdrop-blur-xl transition hover:bg-white/[.12]">Hablar con un asesor</WhatsAppContact></div>
              <div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-xs font-semibold text-white/55">{["Atención en Ecuador", "Evaluación técnica previa", "Trazabilidad de muestras"].map(item=><span key={item} className="flex items-center gap-2"><BadgeCheck className="h-4 w-4 text-[#83e2c2]" />{item}</span>)}</div>
            </motion.div>
            <motion.div initial={{opacity:0,x:25}} animate={{opacity:1,x:0}} transition={{delay:.12,duration:.8}} className="relative h-[360px] sm:h-[450px]">
              <div className="absolute inset-x-0 top-0 h-[88%] overflow-hidden rounded-[30px] border border-white/10 shadow-[0_35px_90px_rgba(0,0,0,.3)] sm:left-8"><Image src="/modern-laboratory-scientists.png" alt="Equipo de biología molecular de AS Labs Ecuador" fill priority className="object-cover" sizes="(min-width:1024px) 46vw,100vw" /><div className="absolute inset-0 bg-gradient-to-t from-[#061a15]/75 via-transparent to-transparent" /><motion.div animate={{x:["-30%","620%"]}} transition={{duration:6,repeat:Infinity,ease:"linear",repeatDelay:1}} className="absolute inset-y-0 left-0 w-[14%] bg-gradient-to-r from-transparent via-[#a1ead2]/20 to-transparent" /></div>
              <div className="absolute bottom-0 left-0 right-8 rounded-[24px] border border-white/15 bg-[#0b3028]/90 p-5 shadow-2xl backdrop-blur-xl sm:left-0 sm:right-auto sm:w-[310px]"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-[#f2d77e]">Sede Ecuador</p><div className="mt-3 flex gap-3"><MapPin className="mt-0.5 h-5 w-5 shrink-0 text-[#8ce3c6]" /><div><strong className="block text-sm">Edificio Carolina Millenium</strong><span className="mt-1 block text-xs leading-5 text-white/60">Andrade Marin 24<br />170518 Quito, Ecuador</span></div></div></div>
            </motion.div>
          </div>
        </section>

        <section id="servicios-ecuador" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28">
          <div className="grid gap-7 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#33836d]">Portafolio Ecuador</p><h2 className="mt-4 max-w-4xl text-balance text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Dos áreas, una misma exigencia científica</h2></div><p className="text-sm leading-7 text-[#65766f]">La sede Ecuador inicia operaciones con capacidades específicas. El resto del portafolio permanece disponible únicamente desde Perú.</p></div>
          <div className="mt-12 grid gap-5 lg:grid-cols-2">{solutions.map((solution,index)=><motion.article key={solution.href} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.1}} className="group overflow-hidden rounded-[32px] border border-black/[.07] bg-white shadow-[0_18px_60px_rgba(15,55,45,.08)]"><Link href={solution.href} className="grid min-h-[500px] sm:grid-cols-[.48fr_.52fr]"><div className="relative min-h-[260px] overflow-hidden"><Image src={solution.image} alt={solution.title} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(min-width:640px) 28vw,100vw" /><div className="absolute inset-0 bg-gradient-to-t from-[#0a2c24]/65 to-transparent" /><span className="absolute left-5 top-5 grid h-12 w-12 place-items-center rounded-2xl border border-white/20 bg-[#0a3027]/70 text-white backdrop-blur-xl"><solution.icon className="h-5 w-5" /></span></div><div className="flex flex-col p-6 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#35856e]">{solution.eyebrow}</p><h3 className="mt-3 text-3xl font-semibold tracking-[-.035em]">{solution.title}</h3><p className="mt-4 text-sm leading-7 text-[#687a73]">{solution.description}</p><div className="mt-6 flex flex-wrap gap-2">{solution.tags.map(tag=><span key={tag} className="rounded-full bg-[#edf5f1] px-3 py-2 text-[10px] font-bold text-[#3e695d]">{tag}</span>)}</div><span className="mt-auto flex items-center gap-2 pt-8 text-sm font-bold text-[#256d59]">Ver área especializada<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></span></div></Link></motion.article>)}</div>
        </section>

        <section className="bg-white py-20 sm:py-28"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div className="relative min-h-[420px] overflow-hidden rounded-[32px]"><Image src="/research/research-lab.png" alt="Laboratorio de AS Labs Ecuador" fill className="object-cover" sizes="(min-width:1024px) 44vw,100vw" /><div className="absolute inset-0 bg-gradient-to-t from-[#08231d]/70 to-transparent" /><div className="absolute bottom-6 left-6 right-6 rounded-2xl border border-white/15 bg-black/15 p-5 text-white backdrop-blur-xl"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#9ae7cd]">Quito · Ecuador</p><p className="mt-2 text-lg font-semibold">Una base local para proyectos de alcance nacional</p></div></div><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#33836d]">Nuestra ubicación</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.045em] sm:text-5xl">AS Labs Ecuador</h2><div className="mt-8 rounded-[28px] border border-[#d7e4dc] bg-[#f2f7f4] p-6 sm:p-8"><div className="flex gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#173f32] text-[#e5bd45]"><Building2 className="h-5 w-5" /></span><div><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#6e8077]">Edificio</p><h3 className="mt-2 text-xl font-bold">Carolina Millenium</h3><p className="mt-3 text-sm leading-7 text-[#5f736a]">Andrade Marin 24<br />170518 Quito, Ecuador</p></div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[{icon:Microscope,title:"Análisis especializados",text:"Flujos definidos según muestra y objetivo."},{icon:Atom,title:"Desarrollos técnicos",text:"Evaluación de factibilidad para proyectos."}].map(item=><div key={item.title} className="rounded-2xl border border-black/[.07] p-5"><item.icon className="h-5 w-5 text-[#30826b]" /><h3 className="mt-4 text-sm font-bold">{item.title}</h3><p className="mt-2 text-xs leading-5 text-[#6b7b74]">{item.text}</p></div>)}</div></div></div></section>

        <section className="px-5 py-20 sm:px-8 sm:py-24"><div data-navbar-theme="dark" className="relative mx-auto max-w-7xl overflow-hidden rounded-[38px] bg-[#0b2b24] p-7 text-white sm:p-12"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full border-[40px] border-[#e5bd45]/[.06]" /><div className="relative flex flex-col gap-8 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#f0d477]">Ecuador</p><h2 className="mt-4 max-w-3xl text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Cuéntanos qué necesitas analizar o desarrollar</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-white/60">Revisaremos tu objetivo, tipo de muestra, volumen y alcance antes de proponer el siguiente paso.</p></div><WhatsAppContact mode="modal" message="Hola, quisiera evaluar un proyecto con AS Labs Ecuador." className="inline-flex min-h-14 shrink-0 items-center justify-center gap-3 rounded-full bg-[#e5bd45] px-7 text-sm font-bold text-[#173428] transition hover:-translate-y-1 hover:bg-[#f2d77e]">Evaluar mi proyecto<ArrowRight className="h-4 w-4" /></WhatsAppContact></div></div></section>
      </main>
      <EcuadorFooter />
    </div>
  )
}
