import type { Metadata } from "next"
import EcuadorServiceClient, { type EcuadorServiceItem } from "@/components/ecuador-service-client"

export const metadata: Metadata = {
  title: "Biología Molecular en Quito, Ecuador | AS Labs Ecuador",
  description: "Recepción y coordinación en Quito para PCR, qPCR, RT-PCR, 16S rRNA, ITS, Sanger, genoma completo, genotipado y bioinformática procesados en AS Labs Perú.",
  keywords: ["biología molecular Quito", "PCR Ecuador", "16S rRNA Ecuador", "secuenciamiento genoma completo Ecuador", "qPCR Quito", "secuenciamiento Sanger Ecuador", "identificación molecular Ecuador", "extracción ADN Ecuador", "bioinformática Ecuador"],
  alternates: { canonical: "https://aslaboratorios.com/ecuador/biologia-molecular", languages: { "es-EC": "https://aslaboratorios.com/ecuador/biologia-molecular" } },
  openGraph: { locale: "es_EC", url: "https://aslaboratorios.com/ecuador/biologia-molecular", title: "Biología Molecular | AS Labs Ecuador", description: "Análisis moleculares especializados, desde la preparación de muestras hasta la interpretación bioinformática.", images: ["/research/research-lab.png"] },
}

const molecularServices: EcuadorServiceItem[] = [
  { title: "Secuenciamiento de genoma completo (WGS)", category: "Secuenciamiento", summary: "Caracterización genómica de aislados para investigación, comparación y evaluación de diversidad.", scope: ["Revisión de calidad del material genético", "Definición de profundidad y estrategia", "Entrega de archivos y resultados según alcance"] },
  { title: "Identificación bacteriana mediante 16S rRNA", category: "Identificación", summary: "Identificación taxonómica de bacterias mediante amplificación y secuenciamiento de regiones del gen 16S rRNA.", scope: ["Extracción o recepción de ADN", "Amplificación y control del producto", "Comparación de secuencia e informe"] },
  { title: "Identificación de hongos mediante región ITS", category: "Identificación", summary: "Identificación molecular de hongos y levaduras mediante secuenciamiento de regiones ITS.", scope: ["Evaluación de muestra o cultivo", "Amplificación de marcador ITS", "Análisis comparativo e interpretación"] },
  { title: "Secuenciamiento Sanger", category: "Secuenciamiento", summary: "Lectura dirigida de amplicones o fragmentos para confirmación, identificación y validación puntual.", scope: ["Revisión de amplicón o ADN", "Purificación y reacción de secuencia", "Entrega de cromatograma y secuencia"] },
  { title: "PCR convencional", category: "Detección", summary: "Detección cualitativa de secuencias objetivo mediante protocolos y controles definidos para cada matriz.", scope: ["Selección o validación del blanco", "Control positivo, negativo y de reacción", "Registro e interpretación del resultado"] },
  { title: "qPCR en tiempo real", category: "Detección", summary: "Detección sensible y seguimiento cuantitativo o relativo de blancos moleculares específicos.", scope: ["Diseño del esquema analítico", "Curva y controles según el objetivo", "Análisis de amplificación e informe"] },
  { title: "RT-PCR y RT-qPCR", category: "Detección", summary: "Evaluación de blancos de ARN para detección molecular y proyectos de expresión génica.", scope: ["Extracción y control de ARN", "Retrotranscripción y amplificación", "Interpretación según diseño experimental"] },
  { title: "Diagnóstico molecular de patógenos agrícolas", category: "Sanidad vegetal", summary: "Detección dirigida de patógenos en tejido vegetal, suelo, agua u otras matrices compatibles.", scope: ["Revisión de síntomas y matriz", "Selección del método molecular", "Resultado con trazabilidad de muestra"] },
  { title: "Genética e identidad vegetal", category: "Genética", summary: "Evaluación de identidad, uniformidad o relación genética en material vegetal según marcadores disponibles.", scope: ["Definición de pregunta genética", "Selección de marcadores", "Comparación e interpretación técnica"] },
  { title: "Genotipado con marcadores moleculares", category: "Genética", summary: "Caracterización comparativa mediante marcadores para diversidad, selección o diferenciación de materiales.", scope: ["Diseño de muestreo", "Selección del panel de marcadores", "Matriz comparativa de resultados"] },
  { title: "Extracción y control de calidad de ADN o ARN", category: "Preparación", summary: "Obtención y evaluación de ácidos nucleicos desde matrices vegetales, microbianas y ambientales compatibles.", scope: ["Selección del protocolo de extracción", "Cuantificación y evaluación de pureza", "Conservación o preparación para análisis"] },
  { title: "Diseño y validación de primers", category: "Desarrollo", summary: "Diseño in silico y evaluación experimental de iniciadores para blancos moleculares definidos.", scope: ["Selección de secuencia objetivo", "Evaluación de especificidad", "Optimización preliminar de condiciones"] },
  { title: "Análisis bioinformático y filogenético", category: "Bioinformática", summary: "Procesamiento, comparación y organización de secuencias para responder preguntas taxonómicas o evolutivas.", scope: ["Control y depuración de secuencias", "Alineamiento y comparación", "Árbol o informe según el alcance"] },
  { title: "Evaluación de metabarcoding y metagenómica", category: "Bioinformática", summary: "Revisión de viabilidad para estudiar comunidades microbianas mediante estrategias de secuenciamiento masivo.", scope: ["Definición de matriz y pregunta", "Selección de marcador o enfoque", "Propuesta técnica y bioinformática"] },
]

export default function BiologiaMolecularEcuadorPage() {
  return <EcuadorServiceClient kind="molecular" eyebrow="Biología molecular" title="Respuestas moleculares para preguntas complejas" description="Coordinamos la recepción de muestras y el alcance técnico desde Quito. Los análisis, la amplificación y el secuenciamiento se realizan en nuestros laboratorios especializados del Perú." image="/research/research-lab.png" services={molecularServices} methods={["Recepción y revisión técnica desde Quito", "Extracción y control de calidad de ADN o ARN", "PCR convencional, qPCR y RT-PCR", "Marcadores 16S rRNA, ITS y genéticos", "Secuenciamiento Sanger o de genoma completo", "Controles técnicos y análisis bioinformático en Perú"]} deliverables={["Informe técnico de resultados", "Trazabilidad e identificación de muestras", "Archivos de secuencia según el servicio", "Resultados de comparación bioinformática", "Interpretación dentro del alcance contratado", "Orientación técnica posterior a la entrega"]} />
}
